### ISSUE TITLE
Temperature conversion tool

### ISSUE THREAD

**Issue by sourcefactory-at** [codeezzi/utility#13]
# Create a Temperature conversion tool in html,css and javascript.
--

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
--

## check the options that you have completed,  

I have;
- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by sanyud24** [comment]
can you assign this to me?

**Comment by programmerraja** [comment]
Is still open can i work on it ?
