### ISSUE TITLE
Bug in template.js

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#134]
## Description : 
 when we try to navigate from one tool to another, for example if we are on density conversion tool ##### PATH `/conversionTools/density/density.html` and we try to navigate to energy conversion tool  then it is unable to get the path because the path that gets passed is `/conversionTools/density/conversionTools/Energy/energy.html` instead of `/conversionTools/Energy/energy.html`.

- I think the bug is on the `node generator function` on line `33-40` in `assets/scripts/template.js`
- The function is returning the URL as `category + tool.url` , which is very well working for the index.html. But on the other files it adds the category twice which is why we are unable to get the URL.

@negarjf  Try to solve the problem 
- Anyone can contribute to this issue but before making a pull request discuss your solution in the comment section of this issue here, with @shubham2704 or @negarjf

**Comment by xstable** [comment]
I'll have a look at this.
