### ISSUE TITLE
Add Hacktober Fest label to the Repository Description

### ISSUE THREAD

**Issue by negarjf** [codeezzi/utility#17]
## Problem
After creating my first PR to this repository, in my Hactober Fest profile, I have noticed that the repository is not recognized as a Hacktober fest repo.

<img width="708" alt="Screenshot 2020-10-06 at 10 11 09" src="https://user-images.githubusercontent.com/24963113/95176519-456e4500-07bd-11eb-97f5-6fe14ef3b670.png">
<img width="715" alt="Screenshot 2020-10-06 at 10 11 19" src="https://user-images.githubusercontent.com/24963113/95176535-4a32f900-07bd-11eb-95b2-3b584f12d1ce.png">

## Solution
In order to fix that we need to add `hacktoberfest` label to the repository description as explained in [this video](https://youtu.be/FxBv4FMcDgo?t=35).

I think only @shubham2704 is able to make this change.

**Comment by shubham2704** [comment]
@negarjf  It is already added to the repo. Very sorry  this happened I will figure it out what happened .

**Comment by shubham2704** [comment]
> @negarjf It is already added to the repo. Very sorry this happened I will figure it out what happened .

i think the issue is solved.
@negarjf make a new PR with same changes and i will accept it.
