### ISSUE TITLE
Add contributors.html page 

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#18]
#  Create in contributors.html page html,css and javascript.
contributors.html page will be the page for listing all the contributors who have contributed to this repository.

--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] Linked my tool to the index.html file
- [ ] updated readme.md

**Comment by purnima143** [comment]
Can I work on this issue?

**Comment by shubham2704** [comment]
> Can I work on this issue?

Yes sure. Go Ahead.

**Comment by purnima143** [comment]
@shubham2704  Could you tell me what all the stuff should be there in the contributors.html page?

**Comment by shubham2704** [comment]
- you have to design a page that will contain the names of every contributor who have contributed to this repo. make sure you 
  follow the current design theme and make the page accordingly.
- Link the page in the footer section of the `index.html`  page beside the `Terms of Use`.
- (currently add the name of the contributors that are listed on this page `https://github.com/codeezzi/utility` under Contributors   
   section.  Also add the link to the profile of the contributor.)

**Comment by purnima143** [comment]
@shubham2704  I made a PR. Kindly check it.

**Comment by shubham2704** [comment]
> @shubham2704 I made a PR. Kindly check it.

Thank you @purnima143 for the contribution your changes are currently in review. your PR will be merged as the review phase is over.
