### ISSUE TITLE
Percentage Calculator as a part of Mathematical Tools

### ISSUE THREAD

**Issue by adata111** [codeezzi/utility#23]
#  Create a percentage calculator in html,css and javascript.

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] updated readme.md

**Comment by adata111** [comment]
Could you please assign me to this issue?

**Comment by shubham2704** [comment]
> Could you please assign me to this issue?

Also update the readme file and add percentage calculator to the list. in your PR
