### ISSUE TITLE
currency conversion tool

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#3]
#  Create a currency conversion tool in html,css and javascript.

--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] Linked my tool to the index.html file
- [ ] updated readme.md

**Comment by ramonborges15** [comment]
I would like to work on this issue. @shubham2704

**Comment by Asies23** [comment]
Can I work on this issue?
