### ISSUE TITLE
Image/JPG to PNG conversion tool

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#34]
#  Create a Image/JPG to PNG conversion tool in html,css and javascript.

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by lmigula** [comment]
I would like to help on this one :)

**Comment by shubham2704** [comment]
@lmigula read the new guidelines:

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
