### ISSUE TITLE
Resistence conversion tool

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#36]
#  Create a Resistence conversion tool in html,css and javascript.

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by RahulSahOfficial** [comment]
Hi, I would like to work on this.
_(I had previously made the pressure and power convertor)_
