### ISSUE TITLE
Angle conversion tool

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#39]
#  Create a Angle conversion tool in html,css and javascript.

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by mrunalvilas** [comment]
can I work on this issue

**Comment by mrunalvilas** [comment]
thanks a lot

**Comment by shubham2704** [comment]
@mrunalvilas read the new guidelines:

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **

**Comment by mrunalvilas** [comment]
hey I haven't seen anyone updating readme for the features, where should i add the description of the tool i am adding?

**Comment by shubham2704** [comment]
@mrunalvilas don't worry on that it will be added by our team.
 🎉 Good work on the PR 🥇
