### ISSUE TITLE
speed conversion tool

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#4]
#  Create a speed conversion tool in html,css and javascript.

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] Linked my tool to the index.html file
- [ ] updated readme.md

**Comment by ramonborges15** [comment]
Can I work on this issue?

**Comment by shubham2704** [comment]
@ramonborges15 are you still working on this?

**Comment by shubham2704** [comment]
@ramonborges15 read the new guidelines:
- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **

**Comment by ramonborges15** [comment]
@shubham2704 yes. I'm trying conciliate my job's tasks and this issue.

**Comment by shubham2704** [comment]
@ramonborges15 No problem! As our contributing guidelines have been changed so read them before and make changes accordingly before makin the pull request. ✌

**Comment by ramonborges15** [comment]
@shubham2704 Ok, i will read them ✌!

**Comment by shubham2704** [comment]
@ramonborges15 are you still working on this issue.

**Comment by ramonborges15** [comment]
@shubham2704  I did it. But I have a problem. Since last Saturday I'm facing it but without success.
![image](https://user-images.githubusercontent.com/13764188/96040559-e5247680-0e40-11eb-81d5-0ff3269a4942.png)

**Comment by ramonborges15** [comment]
@shubham2704 The problem was solved. I already created the PR.
