### ISSUE TITLE
Torque conversion tool

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#40]
#  Create a Torque conversion tool in html,css and javascript.

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by saurabhhere** [comment]
Hi @shubham2704 , Can you assign this to me?
Also do you need any specific styling for this or should I go with same as others.

**Comment by shubham2704** [comment]
@saurabhhere you have to follow the design theme of index.html or you can make something creative that looks even better than that.
-  And follow the contributing guidelines.
