### ISSUE TITLE
Density Conversion Tool

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#42]
#  Create a Density conversion tool in html,css and javascript.

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by kushaangowda** [comment]
Hi @shubham2704, can you please assign this to me?

**Comment by kushaangowda** [comment]
Can you please assign this to me?

**Comment by kushaangowda** [comment]
Hi @shubham2704, have added a new PR where I have created the converting tool. Can you please check it?

**Comment by shubham2704** [comment]
@kushaangowda  read the new guidelines:

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **

**Comment by kushaangowda** [comment]
In index.html, had made a change to link it to density converting page, should i change it back to its original state?

**Comment by shubham2704** [comment]
@kushaangowda yes change it back to the original state because changes in index.html creating many conflicts. and sometimes people remove others link and add their ones that's way we decided this rule.

don't worry your tool will be added by our side .

**Comment by kushaangowda** [comment]
I have added a new PR @shubham2704. Please check it. If you want me to change anything, please let me know
