### ISSUE TITLE
Fuel Efficiency calculator

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#43]
#  Create a Fuel Efficiency calculator tool in html,css and javascript.

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by summerag** [comment]
Can I help on this one?

**Comment by bbodenheimer** [comment]
Looking into this

**Comment by shubham2704** [comment]
@bbodenheimer read the new guidelines:

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **

**Comment by bbodenheimer** [comment]
@shubham2704 What is the expected change for the README?

**Comment by shubham2704** [comment]
@bbodenheimer Link your tool in the readme file

**Comment by kartikagarwal9** [comment]
I have created the calculator and sent a PR , please consider it @shubham2704

**Comment by bbodenheimer** [comment]
@shubham2704 Thanks! Updated the README and realized the tool was in the wrong folder, so that's updated now as well
