### ISSUE TITLE
compound interest calculator

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#44]
#  Create a compound interest calculator in html,css and javascript.

--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] Linked my tool to the index.html file
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by OMEGAeNcore** [comment]
Please assign me to this issue.
