### ISSUE TITLE
Stock Return calculator

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#45]
#  Create a Stock Return calculator in html,css and javascript.

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by Salonii02** [comment]
I would like to work on this .

**Comment by shubham2704** [comment]
@Salonii02 Yeah sure. 👩‍💻

**Comment by Salonii02** [comment]
@shubham2704 
This is how the calculator is shaping up.
Please tell me if we can more parameters to calculate stock return value.
If this fine for you I will send PR.
Thank you.
![Screenshot from 2020-10-13 21-08-56](https://user-images.githubusercontent.com/61061499/95883267-5eb45a00-0d98-11eb-8956-6fd0603f0afa.png)

**Comment by shubham2704** [comment]
> @shubham2704
> This is how the calculator is shaping up.
> Please tell me if we can more parameters to calculate stock return value.
> If this fine for you I will send PR.
> Thank you.
> ![Screenshot from 2020-10-13 21-08-56](https://user-images.githubusercontent.com/61061499/95883267-5eb45a00-0d98-11eb-8956-6fd0603f0afa.png)

Looks good, just fix the footer, and if you could add parameters like time period, return rate then try adding them otherwise it's fine. ✔

**Comment by Salonii02** [comment]
Okay sure I will try to add them.
Can you tell what's wrong in footer part?

**Comment by shubham2704** [comment]
Footer Should be fixed to the bottom currently it is too  big. Adding the reference image.
![Capture](https://user-images.githubusercontent.com/40126673/95892661-7560ae00-0da4-11eb-863a-077937d5d4b3.PNG)

**Comment by Salonii02** [comment]
Now okay?
![Screenshot from 2020-10-13 23-26-28](https://user-images.githubusercontent.com/61061499/95897683-8d87fb80-0dab-11eb-881d-6610492714ef.png)

**Comment by shubham2704** [comment]
> Now okay?
> ![Screenshot from 2020-10-13 23-26-28](https://user-images.githubusercontent.com/61061499/95897683-8d87fb80-0dab-11eb-881d-6610492714ef.png)

Nicely Done. 👍

**Comment by Salonii02** [comment]
Hey @shubham2704 
I have added PR.
Please review it.
Thank you.
