### ISSUE TITLE
Mortage calculator

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#46]
#  Create a Mortage calculator in html,css and javascript.

--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] Linked my tool to the index.html file
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by roycebradley** [comment]
Hey @shubham2704 I will work on this one!

**Comment by KaviyaSenthil** [comment]
Hey @shubham2704  I would like to work on this.

**Comment by shubham2704** [comment]
- currently this issue is assigned to @roycebradley . But you can choose any other issue to work on from here : `https://github.com/codeezzi/utility/issues` . 
-  There are many unassigned issues that you can work on.
