### ISSUE TITLE
E.M.I claculator

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#48]
#  Create a Time E.M.I calculator in html,css and javascript.
- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have bben made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by tusharv** [comment]
@shubham2704 - Please assign this to me.

**Comment by shubham2704** [comment]
@tusharv some new guidelines have been added go through them the main ones are:
- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **

**Comment by tusharv** [comment]
@shubham2704 
Sure I have read your comments, so it's already implemented. 😃 
This is how it's shaping up, I'll send PR soon.

![Screenshot (9)](https://user-images.githubusercontent.com/358703/95470974-0697e500-099f-11eb-82b7-6def4a033d56.png)

**Comment by shubham2704** [comment]
@tusharv good work 🥇
