### ISSUE TITLE
improve the design of index.html

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#5]
#  improve design

--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] Linked my tool to the index.html file
- [ ] updated readme.md

**Comment by kavita121** [comment]
What kind of changes I can make??

**Comment by shubham2704** [comment]
> What kind of changes I can make??

you are free to make any kind of changes until the site looks good. you can add animations, svg, transformation and etc.

**Comment by negarjf** [comment]
I can start working on the home page if anyone else is not working on it.

**Comment by ADHIL-MOHAMMED-P-N** [comment]
@shubham2704 Made some changes in the UI.

**Comment by shubham2704** [comment]
> @shubham2704 Made some changes in the UI.
I have seen your pull request the changes you made are good but,
you should have Read contibuting.md, First. Because before making a pull request you needed to be assigned fort this issue.  currently @negarjf id assigned and working on it.

**Comment by ADHIL-MOHAMMED-P-N** [comment]
@shubham2704 ok got it.

**Comment by purnima143** [comment]
@shubham2704  Can I also work on this issue?

**Comment by ADHIL-MOHAMMED-P-N** [comment]
@shubham2704 made some changes!

**Comment by shubham2704** [comment]
> @shubham2704 made some changes!

@ADHIL-MOHAMMED-P-N Thank you for the contribution, it would take some time to merge you PR. As it's in review phase now.💚

**Comment by ADHIL-MOHAMMED-P-N** [comment]
@shubham2704 Ok
