### ISSUE TITLE
B.M.I calculator

### ISSUE THREAD

**Issue by afiaanjumpreety** [codeezzi/utility#51]
#  Create a B.M.I calculator in html,css and javascript.

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
--

## check the options that you have completed,  

I have;
- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by shubham2704** [comment]
> Hello @shubham2704 , can I please work on the BMI calculator?

Okay go ahead but read these instruction first and make the changes accordingly.

## Add the below mention section to your PR message

## Title

## Number of files/folder added

## changes made

## check the options that you have completed,  

I have;
- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] Linked my tool to the index.html file
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by programmerraja** [comment]
@shubham2704  Bro is still open can i work on it ?

**Comment by shubham2704** [comment]
@programmerraja currently @2apreety18 is working on this. if he's unable to make the calculator i will  assign it to you. Until you can work on other issue. ✌
