### ISSUE TITLE
compass

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#68]
#  Create a compass tool in html,css and javascript.

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
**Note: Only make changes to the folder that you have created for your tool/utility **
--

## check the options that you have completed,  

I have;
- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] Followed the directory Structure
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by aj-ya** [comment]
Hey! I'd like to work on this. Can you assign this to me.

**Comment by soumikbaithalu** [comment]
Hi @shubham2704 this is my first contribution on hacktoberfest and this look perfect project for me can you assign it to me 😊

**Comment by shubham2704** [comment]
@soumik2012 this issue is already completed by @aj-ya but you can try any other open issue. There are still many issues that you can work on. ✌
