### ISSUE TITLE
Morse convertor

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#71]
#  Create a Morse conversion tool in html,css and javascript.

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
**Note: Only make changes to the folder that you have created for your tool/utility **
--

## check the options that you have completed,  

I have;
- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] Followed the directory Structure
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by adata111** [comment]
Can I work on this?
Also by "Moorse" you mean "Morse" right?

**Comment by RahulSahOfficial** [comment]
@adata111 are you still working on this I am interested in this 
@shubham2704 what's the deadline of an assigned job

**Comment by shubham2704** [comment]
@RahulSahOfficial There is no deadline for any of the issues. Once @adata111 reply to your comment it will be clear, or i will assign the issue to both. Till then you can contribute to other issue. ✌

**Comment by adata111** [comment]
> @adata111 are you still working on this I am interested in this
> @shubham2704 what's the deadline of an assigned job

Yes I am working, I'll be making a pr soon
