### ISSUE TITLE
PDF converter

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#80]
#  Create a PDF conversion tool in html,css and javascript. (tool for converting files to PDF format)

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
**Note: Only make changes to the folder that you have created for your tool/utility **
--

## check the options that you have completed,  

I have;
- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] Followed the directory Structure
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by lmigula** [comment]
obviously I would take this one ;)

**Comment by shashwatbangar** [comment]
I would love to work on this project

**Comment by ke3peR007** [comment]
kindly let me know if I can work on it

**Comment by shubham2704** [comment]
@ke3peR007 it's already completed. But you can work on another issues always. ✌
