### ISSUE TITLE
Retirement Calculator

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#9]
#  Create a retirement calculator in html,css and javascript.
- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
--

## I have;

- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] updated readme.md

**Comment by georgioupanayiotis** [comment]
Hello @shubham2704 , can you please assign me ?

**Comment by georgioupanayiotis** [comment]
Hi @shubham2704  opened PR https://github.com/codeezzi/utility/pull/49
