### ISSUE TITLE
Cubic Equations

### ISSUE THREAD

**Issue by shubham2704** [codeezzi/utility#96]
#  Create a Cubic Equation Evaluator in html,css and javascript.

- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **
**Note: Only make changes to the folder that you have created for your tool/utility **
--

## check the options that you have completed,  

I have;
- [ ] Read contibuting.md
- [ ] Followed all the guidelines
- [ ] Followed the directory Structure
- [ ] updated readme.md 
- [ ] add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [ ] provide below mentioned details if you want your name to be added in contributors.html
- [ ] mail, twitter, github profile link.

**Comment by Satyam-kumar-yadav** [comment]
i would like to work forward for this issue

**Comment by Anamika810** [comment]
@Satyam-kumar-yadav are you still working on it?

**Comment by Satyam-kumar-yadav** [comment]
@Anamika810 if you wanna work further you can do it.

**Comment by abhishek-mishra17** [comment]
@shubham2704  I would like to work on this
also should i add the cubic equation evaluator in the mathematical tools right

**Comment by shubham2704** [comment]
@Anamika810 and @abhishek-pes this issue is already completed by @Satyam-kumar-yadav and will be closed soon.

**Comment by abhishek-mishra17** [comment]
oh okay any open issues?? In which I can work on
